services:
  study-platform:
    container_name: study-platform
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - pg

  pg:
    image: postgres:18.1-alpine3.23
    container_name: study-platform-pg
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: popov
      POSTGRES_DB: study-platform
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
